### ISSUE TITLE
Italicised exclaimation ! is slanting the wrong way

### ISSUE THREAD

**Issue by timed0** [aliftype/amiri#187] opened 2020-04-28 10:01 UTC
Exclaimation mark in italic slopes left instead of right. Tested on google fonts and also with the version on amirifont.org

I believe that these Latin chars are derived from CrimsonText but it is ok there. The kerning and ligatures on Amiri are much nicer though.

Amiri:
![image](https://user-images.githubusercontent.com/1508134/80474362-a6107080-8947-11ea-84a4-dcbcd5e8299d.png)

Crimson Text:
![image](https://user-images.githubusercontent.com/1508134/80474643-fc7daf00-8947-11ea-9434-ecfdcda6be0f.png)

**Comment by alerque** [comment] 2020-04-28 11:10
I can't replicate the issue with the exclamation point in Amiri. I actually get a non-italicized glyph in the Italic style:

![image](https://user-images.githubusercontent.com/173595/80481049-643cf580-895a-11ea-81c7-552f098a032b.png)

Test code (typeset in [SILE](https://sile-typesetter.org/)):

```tex
\begin{document}
\font[size=60pt]
\raggedright{
\font[family=Montserrat,size=12pt]{Amiri, 60pt}\break
\font[family=Amiri]{Fresh fish!}\break
\font[family=Amiri,style=Italic]{Fresh fish!}\break
}
\end{document}
```

I suspect the backwards glyph might actually be whatever program you are using doing some kind of fallback action. What are you using anyway?

Meanwhile I thought I would chime in to let you know that the version of Crimson Text you are comparing too is obscenely old. There was a major overhaul released some years after the version you are testing with there (now usually just known as Crimson without the 'Text'). Some years after than just a little while back there was another overhaul, this time including a variable font version, this time released as Crimson Pro.

I don't know which edition Amiri pulled glyphs from, but it seems to be newer that the version you are comparing too. If you goal is a font for Latin output, you're probably better off using one of the newer Crimson sources instead.

Here are samples of 400 weight Roman and Italic styles from each:

![image](https://user-images.githubusercontent.com/173595/80480770-e973da80-8959-11ea-94f4-536abfd55200.png)

Interesting to see that the `fi` ligature is in the Italic for both, but only in the Roman style in Crimson Pro. There are quite a number of other kerning and consistency issues cleaned up as well.

Plus the SILE code used to generate the sample:

```tex
\begin{document}
\font[size=60pt]
\raggedright{
\font[family=Montserrat,size=12pt]{Crimson, 60pt}\break
\font[family=Crimson]{Fresh fish!}\break
\font[family=Crimson,style=Italic]{Fresh fish!}\break
\font[family=Montserrat,size=12pt]{Crimson Pro, 60pt}\break
\font[family=Crimson Pro]{Fresh fish!}\break
\font[family=Crimson Pro,style=Italic]{Fresh fish!}\break
}
\end{document}
```

**Comment by khaledhosny** [comment] 2020-04-28 11:34
I can’t reproduce this either, I get upright exclamation mark as expected:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/93914/80482667-e62a2000-8954-11ea-8d6c-61d5e7d350c5.png">

**Comment by timed0** [comment] 2020-04-28 11:51
The TTFs seem ok on Windows and MS-office but the web fonts are showing up with the incorrect slant. I see it in Chrome, Firefox, Edge (all on Windows). It is the same for both the google fonts page and amirifont.org (if I add an exclamation mark). I'm not sure if the browsers use the TTFs or some other format - maybe that is the difference?

**Comment by khaledhosny** [comment] 2020-04-28 14:33
How are you using the font? Looks like you are getting the old version from Google Fonts.

**Comment by alerque** [comment] 2020-04-28 14:56
@khaledhosny He does have a point that https://www.amirifont.org has the same problem, so however you are getting it there...

![image](https://user-images.githubusercontent.com/173595/80502698-a32e7380-8979-11ea-8da4-095524cebb2d.png)

**Comment by khaledhosny** [comment] 2020-04-28 15:17
The website uses the font from Google Fonts (for simplicity), I can make it use the fonts from the repo. But I thought he meant downloading the fonts from the links on the website, otherwise that is a very complicated way to test the font :)

**Comment by timed0** [comment] 2020-04-28 16:30
I was mistaken to think that the amirifont.org website would be using the latest version. I have converted the latest build 0.112 to woff2 (using font-converter.net) and it's better so I guess it is a problem with google's version. Result is below. The exclamation point is better but I think the numbers are regressed - I am ok with that for now.

![image](https://user-images.githubusercontent.com/1508134/80512177-62385e00-897d-11ea-9ad5-f6154935ec8e.png)

Just to add that we really appreciate the work you have done with this font. We have been using it for both Arabic and Latin content on our blog to book service (pixxibook.com) and it looks great in print.

**Comment by khaledhosny** [comment] 2020-04-28 22:11
Happy this is figured out.

> but I think the numbers are regressed

Can you elaborate?

**Comment by timed0** [comment] 2020-04-28 22:27
> > but I think the numbers are regressed

The numbers aren't italicised. It's the same on the google fonts version but on google fonts version 123ish (with letters) _is_ italicised. In this test case it wasn't. The spacing looks different too.

**Closed as completed** 2020-04-29 00:07 UTC

**Comment by khaledhosny** [comment] 2020-04-29 00:08
Numbers should be slanted, but there was a bug in the OpenType code, should be fixed now. If you don’t like the tabular spacing, you can enable the `pnum` feature which should look better in running text.
