### ISSUE TITLE
Alternate glyph for ئ

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#212] opened 2021-01-30 16:12 UTC
A document submitted to the Unicode Consortium proposed a Kirghiz variant of ئ, which can be seen in aliftype/amiri2#35. Normally the hamza could be placed over the bowl of the Yeh, but in Kirghiz the hamza always placed at the top of the character steam according to this document. So I suggest to create this glyph as localized form.

**Comment by khaledhosny** [comment] 2021-01-30 16:14
Duplicate of aliftype/amiri2#36

**Closed as completed by khaledhosny** 2021-01-30 16:14 UTC

**Comment by KrasnayaPloshchad** [comment] 2021-01-30 17:20
Sorry, I encountered an network error.
