### ISSUE TITLE
Add character variants to Alif and Noon

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#174] opened 2019-06-18 13:33 UTC
I discovered some variants while I saw your image in #150, and I think they could be implemented in Amiri font and accessable via style set. These variants include:
1. Alif with hook, this can be appeared at the end of word if this letter can be joined with preceding letter or tatweel.
![1](https://user-images.githubusercontent.com/10364351/59688327-f74ec000-91cc-11e9-8553-63132960d39b.PNG)
2. Long Noon, this can be appeared as isolated or terminal form.
![2](https://user-images.githubusercontent.com/10364351/59688387-21a07d80-91cd-11e9-9730-9fb2ee5691ae.png)
![3](https://user-images.githubusercontent.com/10364351/59704058-ca110a80-91ea-11e9-9acb-bfbb01fa4b86.png) 
![4](https://user-images.githubusercontent.com/10364351/59704070-d006eb80-91ea-11e9-89c5-a5b2439656b3.PNG)

**Comment by khaledhosny** [comment] 2019-06-18 19:32
No.

**Comment by khaledhosny** [comment] 2019-07-10 01:56
Good candidates for `jalt` feature.

**Comment by khaledhosny** [comment] 2020-11-03 22:55
Duplicate of #147

**Closed as completed by khaledhosny** 2020-11-03 22:55 UTC
Labels: enhancement
